# Generated by Django 4.2.3 on 2023-07-04 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('patient_number', models.IntegerField()),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.department')),
                ('doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.doctors')),
            ],
        ),
    ]
